global:
  resolve_timeout: 5m

route:
  group_by: ['severity']      
  group_wait: 10s             
  group_interval: 30s         
  repeat_interval: 5m          
  receiver: 'AI-SRE'    

receivers:
  - name: 'AI-SRE'
    webhook_configs:
      - url: 'https://webhook.site/5d5ebb46-6044-453d-ba50-eeeb20b35374'
        send_resolved: true   
